package com.corhuila.errorcapa8.travesia_natural.reservations.domain.model;

import com.corhuila.errorcapa8.travesia_natural.reservations.domain.exception.InvalidReservationException;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Aggregate root for the Reservations bounded context.
 * Scope of this cut: creation only (02-domain/entities-and-rules.md, "Aggregate: Reservation").
 * Discount calculation, capacity policy and rescheduling are out of scope (spec 001).
 */
public final class Reservation {

    private final UUID reservationId;
    private final UUID tenantId;
    private final String customerId;
    private final List<ReservedService> reservedServices;
    private final BigDecimal projectedValue;
    private final BigDecimal finalValue;
    private final BigDecimal pendingBalance;
    private final BigDecimal creditBalance;
    private final ReservationStatus reservationStatus;
    private final PaymentStatus paymentStatus;
    private final String paymentMethod;
    private final Instant createdAt;

    private Reservation(UUID reservationId, UUID tenantId, String customerId,
                         List<ReservedService> reservedServices, BigDecimal projectedValue,
                         BigDecimal finalValue, BigDecimal pendingBalance, BigDecimal creditBalance,
                         ReservationStatus reservationStatus, PaymentStatus paymentStatus,
                         String paymentMethod, Instant createdAt) {
        this.reservationId = reservationId;
        this.tenantId = tenantId;
        this.customerId = customerId;
        this.reservedServices = reservedServices;
        this.projectedValue = projectedValue;
        this.finalValue = finalValue;
        this.pendingBalance = pendingBalance;
        this.creditBalance = creditBalance;
        this.reservationStatus = reservationStatus;
        this.paymentStatus = paymentStatus;
        this.paymentMethod = paymentMethod;
        this.createdAt = createdAt;
    }

    /**
     * Creates a new reservation as a commercial projection (HU-RES-001).
     * {@code reservationId} is generated by the caller (application layer, per ADR-002/spec 001
     * decision), not by this factory, so it can be known before persistence.
     */
    public static Reservation create(UUID reservationId, UUID tenantId, String customerId,
                                      BigDecimal projectedValue, List<ReservedService> reservedServices) {
        if (tenantId == null) {
            throw new InvalidReservationException("tenantId is required");
        }
        if (customerId == null || customerId.isBlank()) {
            throw new InvalidReservationException("customerId is required");
        }
        if (reservedServices == null || reservedServices.isEmpty()) {
            throw new InvalidReservationException("at least one reserved service is required");
        }
        if (projectedValue == null || projectedValue.signum() < 0) {
            throw new InvalidReservationException("projectedValue must be a non-negative amount");
        }

        return new Reservation(
                reservationId,
                tenantId,
                customerId,
                List.copyOf(reservedServices),
                projectedValue,
                projectedValue,
                projectedValue,
                BigDecimal.ZERO,
                ReservationStatus.PENDIENTE_DE_PAGO,
                PaymentStatus.SIN_PAGO,
                null,
                Instant.now());
    }

    public UUID reservationId() {
        return reservationId;
    }

    public UUID tenantId() {
        return tenantId;
    }

    public String customerId() {
        return customerId;
    }

    public List<ReservedService> reservedServices() {
        return reservedServices;
    }

    public BigDecimal projectedValue() {
        return projectedValue;
    }

    public BigDecimal finalValue() {
        return finalValue;
    }

    public BigDecimal pendingBalance() {
        return pendingBalance;
    }

    public BigDecimal creditBalance() {
        return creditBalance;
    }

    public ReservationStatus reservationStatus() {
        return reservationStatus;
    }

    public PaymentStatus paymentStatus() {
        return paymentStatus;
    }

    public String paymentMethod() {
        return paymentMethod;
    }

    public Instant createdAt() {
        return createdAt;
    }
}
