package com.corhuila.errorcapa8.travesia_natural.reservations.domain.model;

import com.corhuila.errorcapa8.travesia_natural.reservations.domain.exception.InvalidReservationException;
import com.corhuila.errorcapa8.travesia_natural.reservations.domain.exception.PaymentAlreadyResolvedException;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Aggregate root for the Reservations bounded context.
 * Scope of this cut: creation only (02-domain/entities-and-rules.md, "Aggregate: Reservation").
 * Discount calculation, capacity policy and rescheduling are out of scope (spec 001).
 */
public final class Reservation {

    private final UUID reservationId;
    private final String tenantId;
    private final String customerId;
    private final List<ReservedService> reservedServices;
    private final BigDecimal projectedValue;
    private final BigDecimal finalValue;
    private final BigDecimal pendingBalance;
    private final BigDecimal creditBalance;
    private final ReservationStatus reservationStatus;
    private final PaymentStatus paymentStatus;
    private final String paymentMethod;
    private final Instant createdAt;
    private final BigDecimal pendingTransferAmount;
    private final String transferSupportReference;

    private Reservation(UUID reservationId, String tenantId, String customerId,
                         List<ReservedService> reservedServices, BigDecimal projectedValue,
                         BigDecimal finalValue, BigDecimal pendingBalance, BigDecimal creditBalance,
                         ReservationStatus reservationStatus, PaymentStatus paymentStatus,
                         String paymentMethod, Instant createdAt, BigDecimal pendingTransferAmount,
                         String transferSupportReference) {
        this.reservationId = reservationId;
        this.tenantId = tenantId;
        this.customerId = customerId;
        this.reservedServices = reservedServices;
        this.projectedValue = projectedValue;
        this.finalValue = finalValue;
        this.pendingBalance = pendingBalance;
        this.creditBalance = creditBalance;
        this.reservationStatus = reservationStatus;
        this.paymentStatus = paymentStatus;
        this.paymentMethod = paymentMethod;
        this.createdAt = createdAt;
        this.pendingTransferAmount = pendingTransferAmount;
        this.transferSupportReference = transferSupportReference;
    }

    /**
     * Creates a new reservation as a commercial projection (HU-RES-001).
     * {@code reservationId} is generated by the caller (application layer, per ADR-002/spec 001
     * decision), not by this factory, so it can be known before persistence.
     */
    public static Reservation create(UUID reservationId, String tenantId, String customerId,
                                      BigDecimal projectedValue, List<ReservedService> reservedServices) {
        if (tenantId == null || tenantId.isBlank()) {
            throw new InvalidReservationException("tenantId is required");
        }
        if (customerId == null || customerId.isBlank()) {
            throw new InvalidReservationException("customerId is required");
        }
        if (reservedServices == null || reservedServices.isEmpty()) {
            throw new InvalidReservationException("at least one reserved service is required");
        }
        if (projectedValue == null || projectedValue.signum() < 0) {
            throw new InvalidReservationException("projectedValue must be a non-negative amount");
        }

        return new Reservation(
                reservationId,
                tenantId,
                customerId,
                List.copyOf(reservedServices),
                projectedValue,
                projectedValue,
                projectedValue,
                BigDecimal.ZERO,
                ReservationStatus.PENDIENTE_DE_PAGO,
                PaymentStatus.SIN_PAGO,
                null,
                Instant.now(),
                null,
                null);
    }

    /**
     * Reconstructs a reservation exactly as persisted, without re-validating creation
     * invariants (mismo patrón que {@code CatalogItem.reconstitute(...)}).
     */
    public static Reservation reconstitute(UUID reservationId, String tenantId, String customerId,
                                            List<ReservedService> reservedServices, BigDecimal projectedValue,
                                            BigDecimal finalValue, BigDecimal pendingBalance,
                                            BigDecimal creditBalance, ReservationStatus reservationStatus,
                                            PaymentStatus paymentStatus, String paymentMethod, Instant createdAt,
                                            BigDecimal pendingTransferAmount, String transferSupportReference) {
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                pendingBalance, creditBalance, reservationStatus, paymentStatus, paymentMethod, createdAt,
                pendingTransferAmount, transferSupportReference);
    }

    /**
     * Registra un pago en efectivo (spec 009): debe cubrir exactamente o superar el
     * saldo pendiente en una sola operación; un monto insuficiente se rechaza en vez de
     * aceptarse como abono parcial (esa es la modalidad Abono, no Efectivo).
     */
    public Reservation registerCashPayment(BigDecimal amount) {
        validatePaymentAmount(amount);
        if (amount.compareTo(pendingBalance) < 0) {
            throw new InvalidReservationException(
                    "cash payment must cover the full pending balance; use an installment (Abono) for partial payments");
        }
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                BigDecimal.ZERO, creditBalance, ReservationStatus.CONFIRMADA, PaymentStatus.PAGADO, "Efectivo",
                createdAt, null, null);
    }

    /**
     * Registra un abono (spec 009): puede ser parcial. Si el saldo llega a cero, la
     * reserva queda confirmada igual que un pago en efectivo completo.
     */
    public Reservation registerInstallmentPayment(BigDecimal amount) {
        validatePaymentAmount(amount);
        BigDecimal newPendingBalance = pendingBalance.subtract(amount);
        if (newPendingBalance.signum() < 0) {
            newPendingBalance = BigDecimal.ZERO;
        }
        boolean settled = newPendingBalance.signum() == 0;
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                newPendingBalance, creditBalance,
                settled ? ReservationStatus.CONFIRMADA : reservationStatus,
                settled ? PaymentStatus.PAGADO : PaymentStatus.PARCIAL,
                "Abono", createdAt, null, null);
    }

    /**
     * Registra una transferencia con soporte (spec 009): no aplica el monto todavía,
     * queda a la espera de una decisión explícita (aprobar/rechazar).
     */
    public Reservation registerTransferPayment(BigDecimal amount, String supportReference) {
        validatePaymentAmount(amount);
        if (supportReference == null || supportReference.isBlank()) {
            throw new InvalidReservationException("supportReference is required for a transfer payment");
        }
        if (pendingTransferAmount != null) {
            throw new PaymentAlreadyResolvedException(
                    "a transfer is already awaiting a support decision for reservation: " + reservationId);
        }
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                pendingBalance, creditBalance, reservationStatus, PaymentStatus.EN_VALIDACION, "Transferencia",
                createdAt, amount, supportReference);
    }

    /**
     * Aprueba la transferencia en espera: aplica su monto exactamente igual que un
     * abono.
     */
    public Reservation approveTransferPayment() {
        if (pendingTransferAmount == null) {
            throw new PaymentAlreadyResolvedException(
                    "no transfer is awaiting a support decision for reservation: " + reservationId);
        }
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                pendingBalance, creditBalance, reservationStatus, paymentStatus, paymentMethod, createdAt,
                pendingTransferAmount, transferSupportReference)
                .registerInstallmentPayment(pendingTransferAmount);
    }

    /**
     * Rechaza la transferencia en espera: no modifica el saldo pendiente, solo marca el
     * pago como rechazado.
     */
    public Reservation rejectTransferPayment() {
        if (pendingTransferAmount == null) {
            throw new PaymentAlreadyResolvedException(
                    "no transfer is awaiting a support decision for reservation: " + reservationId);
        }
        return new Reservation(reservationId, tenantId, customerId, reservedServices, projectedValue, finalValue,
                pendingBalance, creditBalance, reservationStatus, PaymentStatus.RECHAZADO, paymentMethod,
                createdAt, null, null);
    }

    private void validatePaymentAmount(BigDecimal amount) {
        if (amount == null || amount.signum() <= 0) {
            throw new InvalidReservationException("payment amount must be a positive value");
        }
    }

    public UUID reservationId() {
        return reservationId;
    }

    public String tenantId() {
        return tenantId;
    }

    public String customerId() {
        return customerId;
    }

    public List<ReservedService> reservedServices() {
        return reservedServices;
    }

    public BigDecimal projectedValue() {
        return projectedValue;
    }

    public BigDecimal finalValue() {
        return finalValue;
    }

    public BigDecimal pendingBalance() {
        return pendingBalance;
    }

    public BigDecimal creditBalance() {
        return creditBalance;
    }

    public ReservationStatus reservationStatus() {
        return reservationStatus;
    }

    public PaymentStatus paymentStatus() {
        return paymentStatus;
    }

    public String paymentMethod() {
        return paymentMethod;
    }

    public Instant createdAt() {
        return createdAt;
    }

    public BigDecimal pendingTransferAmount() {
        return pendingTransferAmount;
    }

    public String transferSupportReference() {
        return transferSupportReference;
    }
}
