package com.corhuila.errorcapa8.travesia_natural.tenants.domain.model;

import com.corhuila.errorcapa8.travesia_natural.tenants.domain.exception.InvalidTenantException;

import java.time.Instant;
import java.util.regex.Pattern;

/**
 * Aggregate root for the Tenant Management bounded context (02-domain/entities-and-rules.md,
 * "Aggregate: Tenant"). Scope of this cut: create, deactivate, reactivate (HU-TEN-001).
 * Visual identity and enabled payment methods are out of scope (spec 002).
 */
public final class Tenant {

    private static final Pattern TENANT_ID_PATTERN = Pattern.compile("^[a-z0-9-]{3,50}$");

    private final String tenantId;
    private final String commercialName;
    private final TenantStatus tenantStatus;
    private final Instant createdAt;
    private final boolean allowCollaboratorSupportValidation;

    private Tenant(String tenantId, String commercialName, TenantStatus tenantStatus, Instant createdAt,
                   boolean allowCollaboratorSupportValidation) {
        this.tenantId = tenantId;
        this.commercialName = commercialName;
        this.tenantStatus = tenantStatus;
        this.createdAt = createdAt;
        this.allowCollaboratorSupportValidation = allowCollaboratorSupportValidation;
    }

    /**
     * Creates a tenant in Activo status (HU-TEN-001 escenario 1). {@code tenantId} is assigned
     * by the Platform Administrator, not autogenerated (spec 002 plan decision).
     */
    public static Tenant create(String tenantId, String commercialName) {
        if (tenantId == null || !TENANT_ID_PATTERN.matcher(tenantId).matches()) {
            throw new InvalidTenantException("tenantId must match " + TENANT_ID_PATTERN.pattern());
        }
        if (commercialName == null || commercialName.isBlank()) {
            throw new InvalidTenantException("commercialName is required");
        }

        return new Tenant(tenantId, commercialName, TenantStatus.ACTIVO, Instant.now(), false);
    }

    /**
     * Reconstructs a tenant from persisted state. No invariant re-validation: data already
     * passed through {@link #create} once.
     */
    public static Tenant reconstitute(String tenantId, String commercialName, TenantStatus tenantStatus,
                                       Instant createdAt, boolean allowCollaboratorSupportValidation) {
        return new Tenant(tenantId, commercialName, tenantStatus, createdAt, allowCollaboratorSupportValidation);
    }

    /**
     * Deactivates the tenant (HU-TEN-001 escenario 2). The reason is not part of the aggregate
     * state; it is recorded only in the audit trail (common/audit), per plan.md.
     */
    public Tenant deactivate() {
        if (tenantStatus == TenantStatus.INACTIVO) {
            throw new InvalidTenantException("tenant is already Inactivo: " + tenantId);
        }
        return new Tenant(tenantId, commercialName, TenantStatus.INACTIVO, createdAt,
                allowCollaboratorSupportValidation);
    }

    /**
     * Reactivates the tenant (HU-TEN-001 escenario 3). Only reachable through this explicit
     * operation — INV-TEN-002: never an implicit side effect of another action.
     */
    public Tenant reactivate() {
        if (tenantStatus == TenantStatus.ACTIVO) {
            throw new InvalidTenantException("tenant is already Activo: " + tenantId);
        }
        return new Tenant(tenantId, commercialName, TenantStatus.ACTIVO, createdAt,
                allowCollaboratorSupportValidation);
    }

    /**
     * Toggles whether an {@code OPERATIONAL_COLLABORATOR} may decide on transfer support
     * (spec 020, PDR line 115). Requires the tenant to be Activo, same precondition as the
     * rest of the tenant's lifecycle operations.
     */
    public Tenant updateCollaboratorSupportValidationPermission(boolean allow) {
        if (tenantStatus != TenantStatus.ACTIVO) {
            throw new InvalidTenantException("tenant must be Activo to change its permissions: " + tenantId);
        }
        return new Tenant(tenantId, commercialName, tenantStatus, createdAt, allow);
    }

    public String tenantId() {
        return tenantId;
    }

    public String commercialName() {
        return commercialName;
    }

    public TenantStatus tenantStatus() {
        return tenantStatus;
    }

    public Instant createdAt() {
        return createdAt;
    }

    public boolean allowCollaboratorSupportValidation() {
        return allowCollaboratorSupportValidation;
    }
}
